#FROM quay.io/nyulibraries/selenium_chrome_headless_ruby:2.5.9-slim-chrome_106
FROM ruby:2.7.8

ENV DOCKER true
ENV INSTALL_PATH /app

RUN groupadd -g 2000 docker -r && \
  useradd -u 1000 -r --no-log-init -m -d $INSTALL_PATH -g docker docker
#USER root

WORKDIR $INSTALL_PATH
RUN chown docker:docker .

RUN wget --no-check-certificate -q -O - https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh > /tmp/wait-for-it.sh \
  && chown docker:docker /tmp/wait-for-it.sh && chmod a+x /tmp/wait-for-it.sh

COPY --chown=docker:docker bin/ bin/
COPY --chown=docker:docker Gemfile Gemfile.lock ./
ARG RUN_PACKAGES="nodejs ruby-mysql2 default-libmysqlclient-dev"
ARG BUILD_PACKAGES="build-essential zlib1g-dev git"
RUN apt-get update && apt-get -y --no-install-recommends install $BUILD_PACKAGES $RUN_PACKAGES \
  && gem install bundler -v '1.16.6' \
  && bundle config --local github.https true \
  && bundle install --without no_docker --jobs 20 --retry 5 \
  && rm -rf /root/.bundle && rm -rf /root/.gem \
  && rm -rf /usr/local/bundle/cache \
  && apt-get --purge -y autoremove $BUILD_PACKAGES \
  && apt-get clean && rm -rf /var/lib/apt/lists/* \
  && chown -R docker:docker /usr/local/bundle

USER docker

COPY --chown=docker:docker . .
RUN bin/rails assets:precompile

EXPOSE 3000/tcp

CMD [ "bundle", "exec", "rake" ]
